repositories:
- name: test-app-chart
  url: ghcr.io/pspurlock07
  oci: true

releases:
- name: test-app-chart
  namespace: {{ .Values.namespace }}
  chart: test-app-chart/test-app
  version: 0.1.0
  values:
  - values/test-app.yaml.gotmpl


environments:
  default:
    values:
      - namespace: edge